### ISSUE TITLE
bugfix argument not accepted

### ISSUE THREAD

**Issue by james-v-wong** [RittmanMead/obi-concurrent-develop#1]
The bugfix argument is not accepted by the obi-merge-git.py script.  The bugfix function exists, but there is no call to it in the main function and it's not allowed in the 'action' argument

**Comment by mineshpatel1** [comment]
Woops, thanks for noticing that, have updated the master branch, v1.01 fixes this.

**Comment by james-v-wong** [comment]
No problem.  It's still not in the a choices list for the action argument.
