### ISSUE TITLE
bugfix argument not accepted

### ISSUE THREAD

**Issue by james-v-wong** [RittmanMead/obi-concurrent-develop#2]
The 'bugfix' choice is not in the action list.

**Comment by mineshpatel1** [comment]
Duplicate of #1

**Comment by mineshpatel1** [comment]
This has been fixed as of v1.01 in `obi-merge-git.py`, see #1 for details. For the SVN version, the workflow is slightly different (because of how SVN works), use `startReleaseHotfix` and `finishReleaseHotfix` to achieve the same goal of merging from a release back into develop.

**Comment by james-v-wong** [comment]
Sorry my mistake.
